### ISSUE TITLE
Cannot authenticate in devcontainer via `azd auth login`

### ISSUE THREAD

**Issue by iMicknl** [pascalvanderheiden/ais-apim-openai#18]
By default, azd auth login tries to redirect back to localhost port 45709, however this one isn't opened in the devcontainer.

![image](https://github.com/pascalvanderheiden/ais-apim-openai/assets/1424596/d0174b7d-4cf3-4060-b7a2-2fa60d7491df)

After adding manually 45709 as a port, it works.

![image](https://github.com/pascalvanderheiden/ais-apim-openai/assets/1424596/9f3b5ca5-8cee-449c-9327-34b4e709fb15)

Am I the only one facing this? Otherwise maybe good to add this port to our devcontainer.

**Comment by azureholic** [comment]
Try removing the HTTPS policy in Edge

https://github.com/Azure/azure-cli/issues/10426

worked for me with AZD as well (not related to devcontainer, but on my local machine)
