### ISSUE TITLE
TenantId should not be hardcoded in ChargebackProxy

### ISSUE THREAD

**Issue by iMicknl** [pascalvanderheiden/ais-apim-openai#20]
https://github.com/pascalvanderheiden/ais-apim-openai/blob/3ab47b790b96343e261efdb8ed17ff38242ef091/src/Azure.OpenAI.ChargebackProxy/EventHub.cs#L19

Is this required? If so; we should make this optional + set it via the config.

**Comment by azureholic** [comment]
TenantId is needed for token validation and is a key in the App Configuration Service

will delete this entire file, since Eventhub is not used anymore by the proxy

**Comment by azureholic** [comment]
TenantId is needed for token validation and is a key in the App Configuration Service

will delete this entire file, since Eventhub is not used anymore.

**Comment by azureholic** [comment]
updated project, deleted file

if you want to use eventhub for chargeback data, create a continues export of loganalytics to eventhub.

https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal#event-hubs

**Comment by azureholic** [comment]
done

**Comment by iMicknl** [comment]
Should I wait with my review, or is it fine to review now+tomorrow and create issues of what I notice?

**Comment by azureholic** [comment]
Just report what you find. This way we can build a backlog and prioritize
