### ISSUE TITLE
Implement DedicatedCapacity first strategy

### ISSUE THREAD

**Issue by iMicknl** [pascalvanderheiden/ais-apim-openai#21]
(feature request)
For Provisioned Throughput deployments, you want to have a fallback to PAYGO for peak demand outside of your capacity. 

Would be good to see if we can implement a custom load balancing rule, see https://microsoft.github.io/reverse-proxy/articles/load-balancing.html.  
**Example in Python**: https://github.com/timoklimmer/powerproxy-aoai/issues

**Thoughts:**
- Managed PTU is assigned to a single model deployment, not to the resource. Thus we should be able to route to different models instead of just URLs. 
- To make this easy we can use the same model name over multiple resources (one for PTU, one for PAYGO)
- It should fallback to PAYGO when PTU hits 429 (https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/quota?tabs=rest#understanding-rate-limits). Do we automatically go to PAYGO after a 429, or do we let the application handle initial retry logic?
- PTU-Managed has different headers than PAYGO for utilization, e.g. `azure-openai-deployment-utilization` and `retry-after-ms`.
- If we want to set a quota per user group per model deployment, do we set this on APIM level or on the ReverseProxy? (or both?)

**Comment by azureholic** [comment]
Round robin loadbalancing is currently implemented. But this needs the same deployment names across all instances.

I’ll have a look what we can do differently
