### ISSUE TITLE
OpenAI-ChargebackProxy - Containerize

### ISSUE THREAD

**Issue by azureholic** [pascalvanderheiden/ais-apim-openai#5]
The OpenAI Chargeback proxy should run as a container.

Add Azure Container App and Azure Container Registry to Bicep modules
Add Dockerfile
Add Build Container Step
Add Deploy to Container App Step

**Comment by pascalvanderheiden** [comment]
@azureholic I think we've covered this. Easy way for deployment is to use the devcontainer which has docker in docker installed for building.

**Comment by azureholic** [comment]
Yep. Done!
