### ISSUE TITLE
OpenAI-ChargebackProxy - How to report

### ISSUE THREAD

**Issue by azureholic** [pascalvanderheiden/ais-apim-openai#6]
OpenAI Chargeback proxy is now sending messages to Eventhub, just like the Azure Function that was proposed.
We should discuss what the end goal of the reporting should be. After eventhub at the moment there is no "next step".

I can think of several options
Feed into storage account 
Feed into a Fabric One Lake 
Feed into CosmosDb

Chargeback report in PowerBI?

**Comment by azureholic** [comment]
Added loganalytics custom table as a source for reporting.
Let's see what we think of this.

**Comment by pascalvanderheiden** [comment]
I love it! Created some nice visuals in dashboard bicep. Lets discuss on more visuals, but as a start.
![dashboard](https://github.com/pascalvanderheiden/ais-apim-openai/assets/16578933/72791cae-4db8-4ab6-93c1-256083be0737)

**Comment by azureholic** [comment]
For now it’s Log Analytics
